# Generated by Django 5.2.4 on 2025-07-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('auth_code', models.CharField(blank=True, max_length=4, null=True)),
                ('auth_code_sent_time', models.DateTimeField(blank=True, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True)),
                ('used_invite_code', models.CharField(blank=True, max_length=6, null=True)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='api.userprofile')),
            ],
        ),
    ]
